steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/fdb-build-tools:6'
    - '--build-arg'
    - 'FDB_VERSION=${_FDB_VERSION}'
    - '--build-arg'
    - 'FDB_CLIENTS_PKG_SHA256SUM=${_FDB_CLIENTS_PKG_SHA256SUM}'
    - '--build-arg'
    - 'FDB_SERVER_PKG_SHA256SUM=${_FDB_SERVER_PKG_SHA256SUM}'
    - '.'
  id: '6'

# Test versions
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '--rm'
    - 'gcr.io/$PROJECT_ID/fdb-build-tools:6'
    - 'fdbserver'
    - '--version'
  wait_for: ['6']

# Tag versions
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'gcr.io/$PROJECT_ID/fdb-build-tools:6'
    - 'gcr.io/$PROJECT_ID/fdb-build-tools'
  wait_for: ['6']
  id: 'latest'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'gcr.io/$PROJECT_ID/fdb-build-tools:6'
    - 'gcr.io/$PROJECT_ID/fdb-build-tools:6.0'
  wait_for: ['6']
  id: '6.0'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'tag'
    - 'gcr.io/$PROJECT_ID/fdb-build-tools:6'
    - 'gcr.io/$PROJECT_ID/fdb-build-tools:6.0.18'
  wait_for: ['6']
  id: '6.0.18'

# Test latest
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '--rm'
    - 'gcr.io/$PROJECT_ID/fdb-build-tools'
    - 'fdbserver'
    - '--version'
  wait_for: ['latest']

substitutions:
  _FDB_VERSION: 6.0.18
  _FDB_CLIENTS_PKG_SHA256SUM: 8cf2070cb3659b0051db4804d0126fe7ce0079e780ba08bd23b7757923c3376e
  _FDB_SERVER_PKG_SHA256SUM: b2f35e94083f615449c3abb4d5499420d2ac1ed58272f6c4496ad857b9b989d3

images:
- 'gcr.io/$PROJECT_ID/fdb-build-tools:latest'
- 'gcr.io/$PROJECT_ID/fdb-build-tools:6'
- 'gcr.io/$PROJECT_ID/fdb-build-tools:6.0'
- 'gcr.io/$PROJECT_ID/fdb-build-tools:6.0.15'
